name: Build Pages and Deploy to GitHubPages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ♨️Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
        
      - name: 🔗Install then Build
        run: |
          yarn
          yarn build
        
      - name: 🚩Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
